
services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      target: production
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/transaction.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      target: worker
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/transaction.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - sqlite_data:/app/data
    depends_on:
      - redis

  scheduler:
    build:
      context: .
      target: scheduler
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/transaction.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - sqlite_data:/app/data
    depends_on:
      - redis

volumes:
  redis_data:
  sqlite_data:
